### ISSUE TITLE
Any objections to making this public?

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/DataScience#1]
Right now this is a private repo. I think in general we should keep all our code for the data science visualizations open so anyone can review and repurpose it (not to mention verify how we get our numbers).

**Comment by jaahumadap** [comment]
I agree!!

**Comment by azvoleff** [comment]
@mcooperci any keys or anything in there we can't make public? If not I will switch it over later today.

**Comment by eric-fegraus** [comment]
I did this...by the way we updated R Studio and Rshiny on the sdsc servers.We might need to adjust it so it can read from your home directories but each user can essentially host their own applications
